// app.config.ts
export default defineAppConfig({
  nuxtIcon: {
    size: '24px', // default <Icon> size applied
    aliases: {
      nuxt: 'logos:nuxt-icon',
      home: 'carbon:home',
      dark: 'carbon:moon',
      light: 'carbon:light',
      github: 'carbon:logo-github',
      check: 'carbon:checkbox',
      checked: 'carbon:checkbox-checked',
      trash: 'carbon:trash-can',
      lightning: 'carbon:lightning',
      dropdown: 'carbon:chevron-down',
      apps: 'carbon:apps',
      dashboard: 'carbon:dashboard',
      cafe: 'carbon:cafe',
      new: 'carbon:add',
      menu: 'ic:twotone-menu',
      menuOpen: 'ic:twotone-menu-open',
      close: 'carbon:close',
      locale: 'carbon:language',
      sidebar: 'carbon:side-panel-close',
      folder: 'carbon:folder',
      screen: 'carbon:screen',
      bookmark: 'carbon:bookmark',
      arrowleft: 'carbon:side-panel-close-filled',
      user: 'carbon:user-avatar',
      setting: 'carbon:settings',
      logout: 'carbon:logout',
      product: 'carbon:product',
      category: 'carbon:category',
      edit: 'carbon:edit',
      delete: 'carbon:trash-can',
      alert: 'carbon:warning-alt',
      qrcode: 'carbon:qr-code',
      upload: 'carbon:cloud-upload',
      checkmark: 'carbon:checkmark',
      warning: 'carbon:warning',
      language: 'carbon:ibm-watson-language-translator',
      search: 'carbon:search',
      cart: 'carbon:shopping-cart',
    },
  },
})
